### ISSUE TITLE
Wifi

### ISSUE THREAD

**Issue by mrsstaceyseigle** [owenosborn/CM3-Basic-PCB#1]
Do this board includes wifi.

**Comment by WaskaLabs** [comment]
No. You'd need an external wifi chip

**Comment by mrsstaceyseigle** [comment]
Great work you have done

Few questions:
1. Does this board have Ethernet. 
2. Can you give me the outer dimensions of this board (width, length and if you know the height of the highest component)

Also if it is not asking for to much is there any way that you can edit this board to include wifi adapter and Ethernet port if one does not already exist. Also is there any way to make the board width smaller like around 50mm wide
